### PR TITLE
Add PSAs for hardened RKE2 clusters

### PR DESCRIPTION
**Pull request by dgiebert**

### CODE REVIEW

**Review by viccuad — APPROVED** [review]
LGTM!

Any reason why not to do the same for cert-manager and rancher-monitoring?

**Comment by dgiebert** [comment]
Good question, but somehow those namespaces work :thinking: 

Let me check that!

**Comment by dgiebert** [comment]
Done :)

**Review by viccuad — APPROVED** [review]
Many thanks! Merging!

**Pull request merged**
